FileCabinet/Controllers/CountryController.cs
using FileCabinet.BLL.Interfaces;
using System;
using System.Web;
using System.Web.Mvc;
using FileCabinet.BLL.DTO;
using AutoMapper;
using FileCabinet.Models;
using System.Net;
using System.Threading.Tasks;

namespace FileCabinet.Controllers
{
    public class CountryController : Controller
    {
        private readonly ICountryService _countryService;

        private readonly IMapper _mapper;
        public CountryController(ICountryService serv)
        {
            _countryService = serv;

            _mapper = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<MilitaryEquipmentViewModel, MilitaryEquipmentDTO>().ReverseMap();
                cfg.CreateMap<CountryViewModel, CountryDTO>().ReverseMap();
                cfg.CreateMap<CategoryMilitaryEquipmentViewModel, CategoryMilitaryEquipmentDTO>().ReverseMap();
                cfg.CreateMap<TypeArmyViewModel, TypeArmyDTO>().ReverseMap();

            }).CreateMapper();
        }

        [Authorize(Roles = "admin")]
        public ActionResult Details(int? id, int? TypeArmyID)
        {
            if (id == null || TypeArmyID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                ViewBag.TypeArmyID = TypeArmyID;

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var reslut = _mapper.Map<CountryDTO, CountryViewModel>(_countryService.Details(id));
                if (reslut == null)
                {
                    return HttpNotFound();
                }
                return View(reslut);
            }
        }

        [Authorize(Roles = "admin")]
        public ActionResult Create(int TypeArmyID)
        {

            ViewBag.TypeArmyID = TypeArmyID;

            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CountryID,Name")] CountryViewModel country, int TypeArmyID, HttpPostedFileBase image)
        {

            ViewBag.TypeArmyID = TypeArmyID;

            if (String.IsNullOrEmpty(country.Name))
            {
                ModelState.AddModelError("Name", "Please enter country name");
            }
            if (image == null)
            {
                ModelState.AddModelError("Image", "Please add image");
            }

            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    country.Image = new byte[image.ContentLength];
                    image.InputStream.Read(country.Image, 0, image.ContentLength);
                }
                var result = _mapper.Map<CountryViewModel, CountryDTO>(country);
                _countryService.Add(result);
                return RedirectToAction("Select", "MilitaryEquipment", new { id = TypeArmyID });
            }
            else
            {
                return View(country);
            }
        }

        public async Task<JsonResult> CheckIfExistsCountry([Bind(Include = "CountryID,Name")] CountryViewModel country)
        {
            var check = _mapper.Map<CountryViewModel, CountryDTO>(country);

            var result = await _countryService.CheckIfExistsCountry(check);

            if (result == false)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }

        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id, int? TypeArmyID)
        {
            if (id == null || TypeArmyID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                ViewBag.TypeArmyID = TypeArmyID;

                var typeArmy = _mapper.Map<CountryDTO, CountryViewModel>(_countryService.ConfimDelete(id));
                if (typeArmy == null)
                {
                    return HttpNotFound();
                }
                return View(typeArmy);
            }
        }

        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id, int TypeArmyID)
        {
            ViewBag.TypeArmyID = TypeArmyID;

            CountryDTO country = _countryService.ConfimDelete(id);
            await _countryService.Delete(country);

            return RedirectToAction("Select", "MilitaryEquipment", new { id = ViewBag.CategoryID });
        }

        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id, int? TypeArmyID)
        {
            if (id == null || TypeArmyID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {

                ViewBag.TypeArmyID = TypeArmyID;
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var country = _mapper.Map<CountryDTO, CountryViewModel>(_countryService.Details(id));
                if (country == null)
                {
                    return HttpNotFound();
                }
                return View(country);
            }
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CountryID,Name,Image")] CountryViewModel country, int TypeArmyID, HttpPostedFileBase image)
        {
            ViewBag.TypeArmyID = TypeArmyID;
            if (ModelState.IsValid)
            {

                if (image != null)
                {
                    country.Image = new byte[image.ContentLength];
                    image.InputStream.Read(country.Image, 0, image.ContentLength);
                }

                var mapped = _mapper.Map<CountryViewModel, CountryDTO>(country);
                _countryService.Update(mapped);
                return RedirectToAction("Select", "MilitaryEquipment", new { id = ViewBag.TypeArmyID });
            }
            else
            {
                return View(country);
            }
        }
    }
}

FileCabinet/Controllers/ReviewController.cs
using FileCabinet.BLL.Interfaces;
using System.Web.Mvc;
using FileCabinet.BLL.DTO;
using AutoMapper;
using FileCabinet.Models;
using System.Net;
using Microsoft.AspNet.Identity;

namespace FileCabinet.Controllers
{
    public class ReviewController : Controller
    {
        private readonly IReviewsService _reviewsService;
        private readonly IMapper _mapper;

        public ReviewController(IReviewsService serv)
        {
            _reviewsService = serv;

            _mapper = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<ReviewsDTO, ReviewsViewModel>().ReverseMap();
                cfg.CreateMap<UserViewModel, UserDTO>().ReverseMap();
                cfg.CreateMap<MilitaryEquipmentDTO, MilitaryEquipmentViewModel>().ReverseMap();

            }).CreateMapper();
        }

        [Authorize]
        public ActionResult AddRating(int? id, int? CategoryID, int? TypeArmyID, int? CountryID)
        {
            if (id == null || TypeArmyID == null || CountryID == null || CategoryID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                ViewBag.id = id;
                ViewBag.SelectedTypeArmyID = TypeArmyID;
                ViewBag.CountryID = CountryID;
                ViewBag.CategoryID = CategoryID;
                return View();
            }
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddRating([Bind(Include = "ReviewsID,Score,Id,MilitaryEquipmentID")] ReviewsViewModel review,
            int id, int CategoryID, int TypeArmyID, int CountryID)
        {
            review.MilitaryEquipmentID = id;
            review.UserProfileId = User.Identity.GetUserId();

            ViewBag.id = id;
            ViewBag.SelectedTypeArmyID = TypeArmyID;
            ViewBag.CountryID = CountryID;
            ViewBag.CategoryID = CategoryID;

            ViewBag.TypeArmyID = TypeArmyID;

            if (ModelState.IsValid)
            {
                try 
                {
                    var result = _mapper.Map<ReviewsViewModel, ReviewsDTO>(review);
                    _reviewsService.AddRating(result);
                    return RedirectToAction("SelectMilitaryEquipment", "MilitaryEquipment", new { ViewBag.id, ViewBag.CategoryID, ViewBag.TypeArmyID, ViewBag.CountryID });
                }
                catch
                {
                    ViewBag.Error = "Вы уже оставляли коментарий";
                    return RedirectToAction("SelectMilitaryEquipment", "MilitaryEquipment", new { ViewBag.id, ViewBag.CategoryID, ViewBag.TypeArmyID, ViewBag.CountryID });
                }
            }

            return View(review);
        }


        [Authorize]
        public ActionResult EditReview(int? id, int? CategoryID, int? TypeArmyID, int? CountryID)
        {
            if (id == null || TypeArmyID == null || CountryID == null || CategoryID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                ViewBag.id = id;
                ViewBag.SelectedTypeArmyID = TypeArmyID;
                ViewBag.CountryID = CountryID;
                ViewBag.CategoryID = CategoryID;

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var typeArmy = _mapper.Map<ReviewsDTO, ReviewsViewModel>(_reviewsService.FindReview(User.Identity.GetUserId(), id));
                if (typeArmy == null)
                {
                    return HttpNotFound();
                }
                return View(typeArmy);
            }
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditReview([Bind(Include = "ReviewsID,Score,Id,MilitaryEquipmentID")] ReviewsViewModel reviewmodel, int id, int CategoryID, int TypeArmyID, int CountryID)
        {
            reviewmodel.MilitaryEquipmentID = id;
            reviewmodel.UserProfileId = User.Identity.GetUserId();

            ViewBag.id = id;
            ViewBag.SelectedTypeArmyID = TypeArmyID;
            ViewBag.CountryID = CountryID;
            ViewBag.CategoryID = CategoryID;
            if (ModelState.IsValid)
            {
                var mapped = _mapper.Map<ReviewsViewModel, ReviewsDTO>(reviewmodel);
                _reviewsService.EditReview(mapped);
                return RedirectToAction("SelectMilitaryEquipment", "MilitaryEquipment", new { id, CategoryID, TypeArmyID, CountryID });
            }
            return View(reviewmodel);
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

FileCabinet/Controllers/TypeArmyController.cs
using FileCabinet.BLL.Interfaces;
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using FileCabinet.BLL.DTO;
using AutoMapper;
using FileCabinet.Models;
using System.Threading.Tasks;
using System.Net;

namespace FileCabinet.Controllers
{
    public class TypeArmyController : Controller
    {
        private readonly ITypeArmyService _typeArmyService;
        private readonly IMapper _mapper;

        public TypeArmyController(ITypeArmyService serv)
        {
            _typeArmyService = serv;

            _mapper = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<MilitaryEquipmentViewModel, MilitaryEquipmentDTO>().ReverseMap();
                cfg.CreateMap<CountryViewModel, CountryDTO>().ReverseMap();
                cfg.CreateMap<CategoryMilitaryEquipmentViewModel, CategoryMilitaryEquipmentDTO>().ReverseMap();
                cfg.CreateMap<TypeArmyViewModel, TypeArmyDTO>().ReverseMap();

            }).CreateMapper();
        }

        [AllowAnonymous]
        public async Task<ActionResult> Index()
        {
            var result = _mapper.Map<IEnumerable<TypeArmyDTO>, IEnumerable<TypeArmyViewModel>>(await _typeArmyService.GetAll());
            return View(result);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TypeArmyID,Name")] TypeArmyViewModel typeArmy, HttpPostedFileBase image)
        {
            if (String.IsNullOrEmpty(typeArmy.Name))
            {
                ModelState.AddModelError("Name", "Please enter type army name");
            }
            if (image == null)
            {
                ModelState.AddModelError("Image", "Please add image");
            }


            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    typeArmy.Image = new byte[image.ContentLength];
                    image.InputStream.Read(typeArmy.Image, 0, image.ContentLength);
                }
                var result = _mapper.Map<TypeArmyViewModel, TypeArmyDTO>(typeArmy);
                _typeArmyService.Add(result);
                return RedirectToAction("Index");
            }
            else
            {
                return View(typeArmy);
            }
        }

        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var typeArmy = _mapper.Map<TypeArmyDTO, TypeArmyViewModel>(_typeArmyService.ConfimDelete(id));
            if (typeArmy == null)
            {
                return HttpNotFound();
            }
            return View(typeArmy);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TypeArmyID,Name,Image")] TypeArmyViewModel typeArmy, HttpPostedFileBase image)
        {
            if (String.IsNullOrEmpty(typeArmy.Name))
            {
                ModelState.AddModelError("Name", "Please enter type army name");
            }

            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    typeArmy.Image = new byte[image.ContentLength];
                    image.InputStream.Read(typeArmy.Image, 0, image.ContentLength);
                }

                var mapped = _mapper.Map<TypeArmyViewModel, TypeArmyDTO>(typeArmy);
                _typeArmyService.Update(mapped);
                return RedirectToAction("Index");
            }
            else
            {
                return View(typeArmy);
            }
        }

        public async Task<JsonResult> CheckIfExistsTypeArmy([Bind(Include = "TypeArmyID,Name")] TypeArmyViewModel typeArmy)
        {
            var check = _mapper.Map<TypeArmyViewModel, TypeArmyDTO>(typeArmy);

            var result = (await _typeArmyService.CheckIfExistsTypeArmy(check));

            if (result == false)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }

        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var typeArmy = _mapper.Map<TypeArmyDTO, TypeArmyViewModel>(_typeArmyService.ConfimDelete(id));
            if (typeArmy == null)
            {
                return HttpNotFound();
            }
            return View(typeArmy);
        }

        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            TypeArmyDTO typeArmy = _typeArmyService.ConfimDelete(id);
            await _typeArmyService.Delete(typeArmy);

            return RedirectToAction("Index");
        }
    }
}

FileCabinet/Views/MilitaryEquipment/Create.cshtml
@model FileCabinet.Models.MilitaryEquipmentViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm(null, null, new { CategoryID = ViewBag.Nav_CategoryID, TypeArmyID = ViewBag.Nav_SelectedTypeArmyID, CountryID = ViewBag.Nav_CountryID }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <div class="form-horizontal">
        <h4>MilitaryEquipment</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryMilitaryEquipmentID, "CategoryMilitaryEquipmentID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryMilitaryEquipmentID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryMilitaryEquipmentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CountryID, "CountryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CountryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CountryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeArmyID, "TypeArmyID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeArmyID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeArmyID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="image" name="image" />

                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back", "SelectCategoryGetMilitaryEquipment", new { CategoryID = ViewBag.Nav_CategoryID, TypeArmyID = ViewBag.Nav_SelectedTypeArmyID, CountryID = ViewBag.Nav_CountryID }, new { @class = "btn btn-primary buttoncfg" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FileCabinet/Views/MilitaryEquipment/Delete.cshtml
@model FileCabinet.Models.MilitaryEquipmentViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MilitaryEquipmentViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MilitaryEquipmentID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MilitaryEquipmentID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryMilitaryEquipmentID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryMilitaryEquipmentID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CountryID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CountryID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeArmyID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeArmyID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-default" /> |
    @Html.ActionLink("Back", "SelectCategoryGetMilitaryEquipment", new { CategoryID = ViewBag.Nav_CategoryID, TypeArmyID = ViewBag.Nav_SelectedTypeArmyID, CountryID = ViewBag.Nav_CountryID }, new { @class = "btn btn-primary buttoncfg" })
</div>
    }
</div>

FileCabinet/Views/MilitaryEquipment/Select.cshtml
@model IEnumerable<FileCabinet.Models.CountryViewModel>

@{
    ViewBag.Title = "Select country";
}

<h2>Select</h2>

@Html.ActionLink("Back", "Index", "TypeArmy", null, new { @class = "btn btn-danger buttoncfg" })
@if (User.IsInRole("admin"))
{
        @Html.ActionLink("Create", "Create", "Country", new { TypeArmyID = ViewBag.TypeArmyID }, new { @class = "btn btn-primary buttoncfg" })
}

<ul style="list-style: none;" class="catalog-grid newul">
    @foreach (var item in Model)
    {
        <li class="items-t">
            <div class="goods-tile" data-title="">
                <img class="imagecc" src="data:image;base64,@System.Convert.ToBase64String(item.Image)" width="193" height="193" />

                <h3 class="forh3">@item.Name</h3>
                <div class="goods-tile__price rating">
                    <p class="goods-tile__price-value rating">
                        @if (User.IsInRole("admin"))
                        {
                            @Html.ActionLink("Select", "SelectCountryGetCategory", new { CountryID = item.CountryID, TypeArmyID = ViewBag.TypeArmyID }, new { @class = "btn btn-primary buttoncfg" })
                            @Html.ActionLink("Edit", "Edit", "Country", new { id = item.CountryID, TypeArmyID = ViewBag.TypeArmyID }, new { @class = "btn btn-primary buttoncfg" })
                            @Html.ActionLink("Delete", "Delete", "Country", new { id = item.CountryID, TypeArmyID = ViewBag.TypeArmyID }, new { @class = "btn btn-danger buttoncfg" })
                        }
                        else
                        {
                            @Html.ActionLink("Select", "SelectCountryGetCategory", new { CountryID = item.CountryID, TypeArmyID = ViewBag.TypeArmyID }, new { @class = "btn btn-primary buttoncfg control-label col-md-12" })
                        }
                    </p>
                </div>
            </div>
        </li>
    }
</ul>

FileCabinet/Views/MilitaryEquipment/SelectCountryGetCategory.cshtml
@model IEnumerable<FileCabinet.Models.CategoryMilitaryEquipmentViewModel>

@{
    ViewBag.Title = "SelectCountryGetCategory";
}

<h2>Select category</h2>

@Html.ActionLink("Back", "Select", "MilitaryEquipment", new { id = ViewBag.SelectedTypeArmyID }, new { @class = "btn btn-danger buttoncfg" })
@if (User.IsInRole("admin"))
{
    @Html.ActionLink("Create", "Create", "CategoryMilitaryEquipment", new { TypeArmyID = ViewBag.SelectedTypeArmyID, CountryID = ViewBag.CountryID }, new { @class = "btn btn-primary buttoncfg" })
}

<ul style="list-style: none;" class="catalog-grid newul">
    @foreach (var item in Model)
    {
        <li class="items-t">
            <div class="goods-tile" data-title="">
                <img class="imagecc" src="data:image;base64,@System.Convert.ToBase64String(item.Image)" width="193" height="193" />

                <h3 class="forh3">@item.Name</h3>
                <div class="goods-tile__price rating">
                    <p class="goods-tile__price-value rating">
                        @if (User.IsInRole("admin"))
                        {
                            @Html.ActionLink("Select", "SelectCategoryGetMilitaryEquipment", new { CategoryID = item.CategoryMilitaryEquipmentID, TypeArmyID = ViewBag.SelectedTypeArmyID, CountryID = ViewBag.CountryID }, new { @class = "btn btn-primary buttoncfg" })
                            @Html.ActionLink("Edit", "Edit", "CategoryMilitaryEquipment", new { id = item.CategoryMilitaryEquipmentID, TypeArmyID = ViewBag.SelectedTypeArmyID, CountryID = ViewBag.CountryID }, new { @class = "btn btn-primary buttoncfg" })
                            @Html.ActionLink("Delete", "Delete", "CategoryMilitaryEquipment", new { id = item.CategoryMilitaryEquipmentID, TypeArmyID = ViewBag.SelectedTypeArmyID, CountryID = ViewBag.CountryID }, new { @class = "btn btn-danger buttoncfg" })
                        }
                        else
                        {
                            @Html.ActionLink("Select", "SelectCategoryGetMilitaryEquipment", new { CategoryID = item.CategoryMilitaryEquipmentID, TypeArmyID = ViewBag.SelectedTypeArmyID, CountryID = ViewBag.CountryID }, new { @class = "btn btn-primary buttoncfg control-label col-md-12" })
                        }
                    </p>
                </div>
            </div>
        </li>
    }
</ul>

FileCabinet/Views/MilitaryEquipment/SelectMilitaryEquipment.cshtml
@model FileCabinet.Models.EquipmentReviewViewModel

@{
    ViewBag.Title = "SelectMilitaryEquipment";
}

<h2>Selected military equipment</h2>

<div>
    @Html.ActionLink("Back to list", "SelectCategoryGetMilitaryEquipment", new { CategoryID = ViewBag.CategoryID, TypeArmyID = ViewBag.SelectedTypeArmyID, CountryID = ViewBag.CountryID }, new { @class = "btn btn-danger buttoncfg" })
    @Html.ActionLink("Back to search", "SearchView", "Home", new { CategoryID = ViewBag.CategoryID, TypeArmyID = ViewBag.SelectedTypeArmyID, CountryID = ViewBag.CountryID }, new { @class = "btn btn-danger buttoncfg" })
    <hr />
    <dl class="dl-horizontal">


        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryMilitaryEquipment.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryMilitaryEquipment.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeArmy.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeArmy.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        @if (Model.Rating > 0)
        {
            <dt>
                Your review
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Score)
            </dd>
        }
        <dt>
            Image
        </dt>
        <dd>
            <img class="imagecc" src="data:image;base64,@System.Convert.ToBase64String(Model.Image)" width="400" height="400" />
        </dd>

    </dl>
</div>

@if (Model.Score == 0 && (User.IsInRole("admin") || User.IsInRole("user")))
{
    @Html.ActionLink("AddRating", "AddRating", "Review", new { id = Model.MilitaryEquipmentID, CategoryID = ViewBag.CategoryID, TypeArmyID = ViewBag.SelectedTypeArmyID, CountryID = ViewBag.CountryID }, new { @class = "btn btn-primary buttoncfg" })
}
else if (Model.Score > 0 && (User.IsInRole("admin") || User.IsInRole("user")))
{
    @Html.ActionLink("EditReview", "EditReview", "Review", new { id = Model.MilitaryEquipmentID, CategoryID = ViewBag.CategoryID, TypeArmyID = ViewBag.SelectedTypeArmyID, CountryID = ViewBag.CountryID }, new { @class = "btn btn-primary buttoncfg" })
}